language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
dist: trusty
sudo: false
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install pydiatra $pyflakes
script:
- python3 -m pydiatra .
- python3 -m pyflakes .
- ./pypi-list-classifiers | grep ' .. Python .. '
- ./pypi-list-projects | grep -C5 -x argparse
- ./pypi-list-projects argparse

# vim:ts=2 sts=2 sw=2 et
