#!/usr/bin/env python3

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import http.client
import os
import re
import signal
import sys
import urllib.request

if sys.version_info < (3, 3):
    raise RuntimeError('Python >= 3.3 is required')

ap = argparse.ArgumentParser()
ap.add_argument('project', metavar='PROJECT', nargs='?')
options = ap.parse_args()

def main():
    if options.project is not None:
        proj = options.project
        url = 'https://pypi.org/simple/{proj}/'.format(
            proj=urllib.parse.quote(proj, safe='')
        )
        try:
            fp = urllib.request.urlopen(url)
        except urllib.error.HTTPError as exc:
            if exc.code == http.client.NOT_FOUND:
                msg = '{prog}: {proj}: not found'.format(prog=ap.prog, proj=proj)
                print(msg, file=sys.stderr)
                sys.exit(1)
            else:
                raise
        else:
            with fp:
                proj = fp.url.split('/')[-2]
                print(proj)
    else:
        search_for_a = re.compile(br'<a href="[^>]*">([^<]+)</a>').search
        with urllib.request.urlopen('https://pypi.org/simple/') as fp:
            for line in fp:
                match = search_for_a(line)
                if match is None:
                    continue
                project = match.group(1)
                project = project.decode('ASCII')
                print(project)

try:
    main()
except BrokenPipeError:
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    os.kill(os.getpid(), signal.SIGPIPE)
    raise

# vim:ts=4 sts=4 sw=4 et
