#!/usr/bin/env python3

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import urllib.request

with urllib.request.urlopen('https://pypi.org/pypi?:action=list_classifiers') as fp:
    for line in fp:
        line = line.decode('ASCII').rstrip()
        print(line)

# vim:ts=4 sts=4 sw=4 et
